#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : R-biglm
Version  : 0.9.3
Release  : 54
URL      : https://cran.r-project.org/src/contrib/biglm_0.9-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/biglm_0.9-3.tar.gz
Summary  : Bounded Memory Linear and Generalized Linear Models
Group    : Development/Tools
License  : GPL-2.0
Requires: R-biglm-lib = %{version}-%{release}
Requires: R-DBI
BuildRequires : R-DBI
BuildRequires : R-leaps
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is basically Alan Miller's modification (AS274) of the other
Gentleman's (AS 75) regression by incremental QR decomposition. It has
been lifted out of the "leaps" package and wrapped with an lm-like
interface to make experimentation easier.

%package lib
Summary: lib components for the R-biglm package.
Group: Libraries

%description lib
lib components for the R-biglm package.


%prep
%setup -q -n biglm
pushd ..
cp -a biglm buildavx2
popd
pushd ..
cp -a biglm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718230780

%install
export SOURCE_DATE_EPOCH=1718230780
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/biglm/DESCRIPTION
/usr/lib64/R/library/biglm/INDEX
/usr/lib64/R/library/biglm/Meta/Rd.rds
/usr/lib64/R/library/biglm/Meta/features.rds
/usr/lib64/R/library/biglm/Meta/hsearch.rds
/usr/lib64/R/library/biglm/Meta/links.rds
/usr/lib64/R/library/biglm/Meta/nsInfo.rds
/usr/lib64/R/library/biglm/Meta/package.rds
/usr/lib64/R/library/biglm/NAMESPACE
/usr/lib64/R/library/biglm/NEWS
/usr/lib64/R/library/biglm/R/biglm
/usr/lib64/R/library/biglm/R/biglm.rdb
/usr/lib64/R/library/biglm/R/biglm.rdx
/usr/lib64/R/library/biglm/help/AnIndex
/usr/lib64/R/library/biglm/help/aliases.rds
/usr/lib64/R/library/biglm/help/biglm.rdb
/usr/lib64/R/library/biglm/help/biglm.rdx
/usr/lib64/R/library/biglm/help/paths.rds
/usr/lib64/R/library/biglm/html/00Index.html
/usr/lib64/R/library/biglm/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/biglm/libs/biglm.so
/V4/usr/lib64/R/library/biglm/libs/biglm.so
/usr/lib64/R/library/biglm/libs/biglm.so
